# Generated by Django 6.0.1 on 2026-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_submissionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AddField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
