# Generated by Django 6.0.1 on 2026-03-07 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_question_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment'),
        ),
    ]
