# Generated by Django 6.0.1 on 2026-03-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1),
        ),
    ]
