# Generated by Django 6.0.1 on 2026-03-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submission',
        ),
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.submissionanswer'),
            preserve_default=False,
        ),
    ]
