# Generated by Django 6.0.1 on 2026-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_feedback_question_remove_feedback_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
