# Generated by Django 6.0.4 on 2026-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='randomize_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
    ]
