# Generated by Django 6.0.4 on 2026-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
