# Generated by Django 6.0.4 on 2026-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_question_allow_multiple_correct_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
