# Generated by Django 6.0.4 on 2026-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_approved',
            field=models.BooleanField(default=True),
        ),
    ]
